import './tasks/chromereload.js'
import './tasks/clean.js'
import './tasks/fonts.js'
import './tasks/images.js'
import './tasks/locales.js'
import './tasks/manifest.js'
import './tasks/pages.js'
import './tasks/scripts.js'
import './tasks/styles.js'
import './tasks/version.js'

import './tasks/build.js'

import './tasks/default.js'
import './tasks/pack.js'
